// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Learning_Space.Models;

public partial class Alarm
{
    public int AlarmId { get; set; }

    public int? CourseId { get; set; }

    public string AlarmType { get; set; }

    public int? TypeId { get; set; }

    public virtual Course Course { get; set; }
}