// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Learning_Space.Models;

public partial class Class
{
    public int ClassId { get; set; }

    public string ClassName { get; set; }

    public virtual ICollection<CourseInClass> CourseInClasses { get; set; } = new List<CourseInClass>();

    public virtual ICollection<StudentInClass> StudentInClasses { get; set; } = new List<StudentInClass>();
}