// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Learning_Space.Models;

public partial class CourseInClass
{
    public int CourseInClass1 { get; set; }

    public int? ClassId { get; set; }

    public int? CourseId { get; set; }

    public virtual Class Class { get; set; }

    public virtual Course Course { get; set; }
}