// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Learning_Space.Models;

public partial class Course
{
    public int CourseId { get; set; }

    public string CourseName { get; set; }

    public string CourseDescription { get; set; }

    public virtual ICollection<Alarm> Alarms { get; set; } = new List<Alarm>();

    public virtual ICollection<CourseInClass> CourseInClasses { get; set; } = new List<CourseInClass>();

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public virtual ICollection<Massage> Massages { get; set; } = new List<Massage>();

    public virtual ICollection<MoreStudy> MoreStudies { get; set; } = new List<MoreStudy>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    public virtual ICollection<Teacher> Teachers { get; set; } = new List<Teacher>();
}