// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Learning_Space.Models;

public partial class LearningSpaceContext : DbContext
{
    public LearningSpaceContext(DbContextOptions<LearningSpaceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alarm> Alarms { get; set; }

    public virtual DbSet<Class> Classes { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<CourseInClass> CourseInClasses { get; set; }

    public virtual DbSet<Lesson> Lessons { get; set; }

    public virtual DbSet<LessonAttend> LessonAttends { get; set; }

    public virtual DbSet<Massage> Massages { get; set; }

    public virtual DbSet<MoreStudy> MoreStudies { get; set; }

    public virtual DbSet<StudentInClass> StudentInClasses { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserTask> UserTasks { get; set; }

    public virtual DbSet<ZoomLesson> ZoomLessons { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Alarm>(entity =>
        {
            entity.HasKey(e => e.AlarmId).HasName("PK__Alarms__43E5EB35C57F3EF8");

            entity.Property(e => e.AlarmId).ValueGeneratedNever();
            entity.Property(e => e.AlarmType)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.HasOne(d => d.Course).WithMany(p => p.Alarms)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__Alarms__CourseId__4BAC3F29");
        });

        modelBuilder.Entity<Class>(entity =>
        {
            entity.HasKey(e => e.ClassId).HasName("PK__Classes__CB1927C0DCCBEE99");

            entity.HasIndex(e => e.ClassName, "UQ__Classes__F8BF561B378B7C99").IsUnique();

            entity.Property(e => e.ClassId).ValueGeneratedNever();
            entity.Property(e => e.ClassName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.CourseId).HasName("PK__Courses__C92D71A7BF9690AA");

            entity.HasIndex(e => e.CourseName, "UQ__Courses__9526E2777EA7C6C7").IsUnique();

            entity.Property(e => e.CourseId).ValueGeneratedNever();
            entity.Property(e => e.CourseDescription)
                .HasMaxLength(400)
                .IsUnicode(false);
            entity.Property(e => e.CourseName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<CourseInClass>(entity =>
        {
            entity.HasKey(e => e.CourseInClass1).HasName("PK__CourseIn__4A93DC462A69DAF4");

            entity.ToTable("CourseInClass");

            entity.Property(e => e.CourseInClass1)
                .ValueGeneratedNever()
                .HasColumnName("CourseInClass");

            entity.HasOne(d => d.Class).WithMany(p => p.CourseInClasses)
                .HasForeignKey(d => d.ClassId)
                .HasConstraintName("FK__CourseInC__Class__440B1D61");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseInClasses)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__CourseInC__Cours__44FF419A");
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.HasKey(e => e.LessonId).HasName("PK__Lessons__B084ACD01C281B33");

            entity.Property(e => e.LessonId).ValueGeneratedNever();
            entity.Property(e => e.LessonSubject)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LessonType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Course).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__Lessons__CourseI__534D60F1");
        });

        modelBuilder.Entity<LessonAttend>(entity =>
        {
            entity.HasKey(e => e.LessonAttendId).HasName("PK__LessonAt__719638B5FF9069F9");

            entity.ToTable("LessonAttend");

            entity.Property(e => e.LessonAttendId).ValueGeneratedNever();

            entity.HasOne(d => d.Lesson).WithMany(p => p.LessonAttends)
                .HasForeignKey(d => d.LessonId)
                .HasConstraintName("FK__LessonAtt__Lesso__571DF1D5");

            entity.HasOne(d => d.User).WithMany(p => p.LessonAttends)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__LessonAtt__UserI__5629CD9C");
        });

        modelBuilder.Entity<Massage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Massages__C87C0C9C617B4AC4");

            entity.Property(e => e.MessageId).ValueGeneratedNever();
            entity.Property(e => e.Content)
                .HasMaxLength(5000)
                .IsUnicode(false);
            entity.Property(e => e.MassageDateTime).HasColumnType("datetime");
            entity.Property(e => e.MassageSubject)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Course).WithMany(p => p.Massages)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__Massages__Course__5DCAEF64");
        });

        modelBuilder.Entity<MoreStudy>(entity =>
        {
            entity.HasKey(e => e.MoreId).HasName("PK__MoreStud__E1C95D2586110CBB");

            entity.Property(e => e.MoreId).ValueGeneratedNever();
            entity.Property(e => e.Content)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.MoreStudySubject)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.MoreStudyUrl)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Course).WithMany(p => p.MoreStudies)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__MoreStudi__Cours__4F7CD00D");
        });

        modelBuilder.Entity<StudentInClass>(entity =>
        {
            entity.HasKey(e => e.StudentInClass1).HasName("PK__StudentI__C9B1915F296DF6A4");

            entity.ToTable("StudentInClass");

            entity.Property(e => e.StudentInClass1)
                .ValueGeneratedNever()
                .HasColumnName("StudentInClass");

            entity.HasOne(d => d.Class).WithMany(p => p.StudentInClasses)
                .HasForeignKey(d => d.ClassId)
                .HasConstraintName("FK__StudentIn__Class__3D5E1FD2");

            entity.HasOne(d => d.User).WithMany(p => p.StudentInClasses)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__StudentIn__UserI__3E52440B");
        });

        modelBuilder.Entity<Task>(entity =>
        {
            entity.HasKey(e => e.TaskId).HasName("PK__Tasks__7C6949B1CB334EBB");

            entity.Property(e => e.TaskId).ValueGeneratedNever();
            entity.Property(e => e.TaskType)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Course).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__Tasks__CourseId__5AEE82B9");
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.HasKey(e => e.TeacherId).HasName("PK__Teachers__EDF25964F4CC1B37");

            entity.Property(e => e.TeacherId).ValueGeneratedNever();

            entity.HasOne(d => d.Course).WithMany(p => p.Teachers)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__Teachers__Course__48CFD27E");

            entity.HasOne(d => d.User).WithMany(p => p.Teachers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Teachers__UserId__47DBAE45");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4CA90715E7");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D105342E8472C4").IsUnique();

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(25)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserTask>(entity =>
        {
            entity.HasKey(e => e.UserTaskId).HasName("PK__UserTask__4EF5961FEFA60ECE");

            entity.ToTable("UserTask");

            entity.Property(e => e.UserTaskId).ValueGeneratedNever();
            entity.Property(e => e.Mark).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Remarks)
                .HasMaxLength(5000)
                .IsUnicode(false);

            entity.HasOne(d => d.Task).WithMany(p => p.UserTasks)
                .HasForeignKey(d => d.TaskId)
                .HasConstraintName("FK__UserTask__TaskId__60A75C0F");

            entity.HasOne(d => d.User).WithMany(p => p.UserTasks)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__UserTask__UserId__619B8048");
        });

        modelBuilder.Entity<ZoomLesson>(entity =>
        {
            entity.HasKey(e => e.ZoomLesson1).HasName("PK__ZoomLess__DC613595BF220B31");

            entity.Property(e => e.ZoomLesson1)
                .ValueGeneratedNever()
                .HasColumnName("ZoomLesson");
            entity.Property(e => e.ZoomUrl)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Lesson).WithMany(p => p.ZoomLessons)
                .HasForeignKey(d => d.LessonId)
                .HasConstraintName("FK__ZoomLesso__Lesso__6477ECF3");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}