// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Learning_Space.Models;

public partial class Lesson
{
    public int LessonId { get; set; }

    public int? CourseId { get; set; }

    public string LessonSubject { get; set; }

    public DateOnly LessonDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public string LessonType { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<LessonAttend> LessonAttends { get; set; } = new List<LessonAttend>();

    public virtual ICollection<ZoomLesson> ZoomLessons { get; set; } = new List<ZoomLesson>();
}