// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Learning_Space.Models;

public partial class LessonAttend
{
    public int LessonAttendId { get; set; }

    public int? LessonId { get; set; }

    public int? UserId { get; set; }

    public bool Attend { get; set; }

    public virtual Lesson Lesson { get; set; }

    public virtual User User { get; set; }
}