// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Learning_Space.Models;

public partial class MoreStudy
{
    public int MoreId { get; set; }

    public int? CourseId { get; set; }

    public string MoreStudySubject { get; set; }

    public string Content { get; set; }

    public string MoreStudyUrl { get; set; }

    public virtual Course Course { get; set; }
}