// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Learning_Space.Models;

public partial class UserTask
{
    public int UserTaskId { get; set; }

    public int? UserId { get; set; }

    public int? TaskId { get; set; }

    public decimal? Mark { get; set; }

    public string Remarks { get; set; }

    public bool Done { get; set; }

    public virtual Task Task { get; set; }

    public virtual User User { get; set; }
}