// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Learning_Space.Models;

public partial class ZoomLesson
{
    public int ZoomLesson1 { get; set; }

    public int? LessonId { get; set; }

    public string ZoomUrl { get; set; }

    public virtual Lesson Lesson { get; set; }
}